Don't use security profiles on el[89]stream and node
oVirt/ost-images pull request #14
Opened 2022-02-09 11:01 UTC by tinez

Security profiles don't work properly on these distros.
We should use them only in rhel8.

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

2022-02-09 11:04 UTC, michalskrivanek commented
what's the actual problem? OPENSCAP_PROFILE is not set for these builds. 
I'd prefer similar/same ks for both

2022-02-09 11:22 UTC, tinez commented
The problem is that now we want to test another security profile, so we'll need to set a value on the OPENSCAP_... parameter and that *will* be propagated to these builds

2022-02-09 12:55 UTC, almusil approved these changes

2022-02-09 14:05 UTC, michalskrivanek commented
I still do not get it. If you set it then yes, it will be propagated. If you do not set, it won't...

2022-02-09 14:07 UTC, michalskrivanek requested changes
that all should be done in build.sh, without touching kickstarts

2022-02-09 15:52 UTC, tinez commented
done

2022-02-09 16:12 UTC, michalskrivanek commented
that's something that's a bit ugly indeed. I don't mind to make this more explicit and e.g. have a different OPENSCAP_PROFILE value to indicate "no profile"

2022-02-10 12:54 UTC, michalskrivanek requested changes

2022-02-10 12:54 UTC, michalskrivanek commented on build.sh
> +    OPENSCAP_PROFILE="${OPENSCAP_PROFILE=xccdf_org.ssgproject.content_profile_stig}" # when unset default to STIG, honor empty var
":=" ?

and just
"# default to STIG"

2022-02-10 12:54 UTC, michalskrivanek commented on build.sh
> +        OPENSCAP_PROFILE= \
we do want it for RHVH too (soon)

2022-02-10 13:54 UTC, tinez commented on build.sh
> +        OPENSCAP_PROFILE= \
Ack, I've changed the approach now

2022-02-10 13:55 UTC, tinez reviewed
This change will be accompanied by a change in jenkins that sets the default value of `OPENSCAP_PROFILE` to `xccdf_org.ssgproject.content_profile_stig`

2022-02-10 16:09 UTC, michalskrivanek approved these changes

2022-02-11 09:18 UTC, merged